version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  node:
    build: ./node.js
    ports:
      - '3000:3000'
      - '443:443'
    tty: true
    depends_on:
      - mysql
volumes:
  db:
